config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get '/s/:slug', to: 'home#redirect_main_url'
  get '/admin/s/:slug', to: 'home#link_details'
  resources :home do 
  	collection do 
  		post 'generate_urls'
  		get 'make_expire'
  	end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
	validates_presence_of :url
  validates :url, format: URI::regexp(%w[http https])
  validates_uniqueness_of :slug
  # validates_length_of :url, within: 3..255, on: :create, message: "too long"
  # validates_length_of :slug, within: 3..255, on: :create, message: "too long"

  def self.shorten(url, slug = '')
  	# return short when URL with that slug was created before
	  link = Link.where(url: url, active: true).first
	  return link.id if link 
	    
	  # create a new
	  slug = SecureRandom.urlsafe_base64(3)
	  link = Link.new(url: url, slug: slug)
	  return link.id if link.save
	end

	def short
	  return "s/#{slug}"
	end

	def make_expired
		self.active = false
		self.save!
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	before_action :set_link, only: [:redirect_main_url, :link_details, :make_expire]

	def index
	end

	def test

	end

	def generate_urls
		id = Link.shorten(params[:url])
		redirect_to action: :show, id: id
	end

	def show
		link = Link.find(params[:id])
		@tiny_url = "#{request.base_url}/#{link.short}"
		@admin_url = "#{request.base_url}/admin/#{link.short}"
	end

	def redirect_main_url
		if @link.present?
			@link.update_attribute(:clicked, @link.clicked + 1)
			redirect_to @link.url and return
		else
			render :file => "#{Rails.root}/public/404.html",  :status => 404
		end
	end

	def link_details
	end

	def make_expire
		@link.make_expired
		redirect_to action: :index
	end

	private 

	def set_link
		@link = if(params[:id])
			Link.where(:id => params[:id], :active => true).first
		else
			Link.where(:slug => params[:slug], :active => true).first
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="main">
	<%= form_tag "home/generate_urls" do %>
		<label>Enter URL:</label>
		<%= text_field_tag :url %>
		<%= submit_tag "Generate" %>
	<% end %>
</div>

app/views/home/link_details.html.erb
<div class="main">
	<table>
		<tr>
			<th>URL</th>
			<th>Clicked</th>
			<th></th>
		</tr>
		<tr>
			<td> <%= "#{request.base_url}/#{@link.short}"%> </td>
			<td> <%= @link.clicked%></td>
			<td> <%= link_to "Make Expire", make_expire_home_index_path(:id => @link.id)%></td>
		</tr>
	</table>
</div>

app/views/home/show.html.erb
<div class="main	">
	<span>Shortened URL: </span> <%= link_to @tiny_url, @tiny_url%>
	<br/>
	<br/>
	<span>Admin URL: </span> <%= link_to @admin_url, @admin_url%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shortener</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application'%>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>